"""Audited ordinary artifact identifiers; numeric baselines are always read live.

Scope evidence: docs/ARTIFACT_ITEM_BASELINES.md. These are configuration IDs,
not verified translations or a promise that every item is normally obtainable.
"""

ARTIFACTS = {
    'EArtifactFlash': ('ArtifactProtectionShock1', 'ArtifactAddRadiation1'),
    'EArtifactSoul': ('ArtifactIncreaseRegenStamina2', 'ArtifactAddRadiation2'),
    'EArtifactSnowflake': ('ArtifactIncreaseRegenStamina1', 'ArtifactAddRadiation1'),
    'GArtifactNightStar': ('ArtifactAdditionalInventoryWeight3', 'ArtifactAddRadiation3', 'ArtifactPenaltyLessWeightEffect3'),
    'EArtifactDummy': ('ArtifactIncreaseRegenStamina1',),
    'CArtifactCrystalThorn': ('ArtifactProtectionRadiation1',),
    'EArtifactBattery': ('ArtifactIncreaseRegenStamina1', 'ArtifactAddRadiation1'),
    'FArtifactCrystal': ('ArtifactProtectionBurn1', 'ArtifactAddRadiation1'),
    'EArtifactMoonlight': ('ArtifactProtectionShock2', 'ArtifactAddRadiation2'),
    'FArtifactMomsBeads': ('ArtifactDegenBleeding2', 'ArtifactAddRadiation2'),
    'EArtifactJellyFish': ('ArtifactIncreaseRegenStamina05', 'ArtifactDegenBleeding05'),
    'EArtifactTow': ('ArtifactIncreaseRegenStamina1', 'ArtifactDegenBleeding1', 'ArtifactAddRadiation2'),
    'EArtifactThunderHedgehog': ('ArtifactProtectionShock2', 'ArtifactProtectionRadiation2'),
    'EArtifactWorm': ('ArtifactProtectionShock05', 'ArtifactDegenBleeding05', 'ArtifactProtectionRadiation1'),
    'EArtifactCloud': ('ArtifactProtectionShock1', 'ArtifactDegenBleeding1', 'ArtifactAddRadiation2'),
    'EArtifactAtom': ('ArtifactProtectionShock3', 'ArtifactAddRadiation3'),
    'EArtifactRazor': ('ArtifactIncreaseRegenStamina2', 'ArtifactDegenBleeding2', 'ArtifactAddRadiation3'),
    'EArtifactSparkler': ('ArtifactProtectionShock1', 'ArtifactProtectionRadiation1'),
    'FArtifactFireBall': ('ArtifactProtectionBurn1', 'ArtifactProtectionRadiation1'),
    'GArtifactGoldFish': ('ArtifactAdditionalInventoryWeight1', 'ArtifactAddRadiation1', 'ArtifactPenaltyLessWeightEffect1'),
    'FArtifactSteak': ('ArtifactDegenBleeding1', 'ArtifactAddRadiation1'),
    'GArtifactStoneDrop': ('ArtifactAdditionalInventoryWeight1', 'ArtifactAddRadiation1', 'ArtifactPenaltyLessWeightEffect1'),
    'FArtifactBakedBolts': ('ArtifactDegenBleeding1', 'ArtifactAdditionalInventoryWeight1', 'ArtifactAddRadiation2', 'ArtifactPenaltyLessWeightEffect1'),
    'FArtifactGlass': ('ArtifactDegenBleeding05', 'ArtifactAdditionalInventoryWeight05', 'ArtifactAddRadiation1', 'ArtifactPenaltyLessWeightEffect05'),
    'FArtifactDeadSponge': ('ArtifactDegenBleeding2', 'ArtifactAddRadiation2'),
    'FArtifactHellishHedgehog': ('ArtifactProtectionBurn1', 'ArtifactAdditionalInventoryWeight1', 'ArtifactAddRadiation2', 'ArtifactPenaltyLessWeightEffect1'),
    'FArtifactPlasma': ('ArtifactProtectionBurn2', 'ArtifactProtectionRadiation2'),
    'FArtifactCandle': ('ArtifactDegenBleeding3', 'ArtifactAddRadiation3'),
    'FArtifactRingOmnipotence': ('ArtifactDegenBleeding4', 'ArtifactAddRadiation4', 'ArtifactProtectionBurn4'),
    'FArtifactFireworks': ('ArtifactProtectionBurn3', 'ArtifactAddRadiation3'),
    'FArtifactCore': ('ArtifactProtectionBurn2', 'ArtifactAdditionalInventoryWeight2', 'ArtifactAddRadiation3', 'ArtifactPenaltyLessWeightEffect2'),
    'FArtifactBurntHunk': ('ArtifactDegenBleeding1', 'ArtifactProtectionRadiation1'),
    'FArtifactResin': ('ArtifactDegenBleeding05', 'ArtifactAdditionalInventoryWeight05'),
    'GArtifactSpring': ('ArtifactAdditionalInventoryWeight2', 'ArtifactAddRadiation2', 'ArtifactPenaltyLessWeightEffect2'),
    'CArtifactPellicle': ('ArtifactProtectionChemicalBurn3', 'ArtifactProtectionRadiation3'),
    'CArtifactChunkMeat': ('ArtifactProtectionChemicalBurn1', 'ArtifactAddRadiation1'),
    'GArtifactGravy': ('ArtifactAdditionalInventoryWeight1', 'ArtifactProtectionRadiation1', 'ArtifactPenaltyLessWeightEffect1'),
    'FArtifactDrops': ('ArtifactProtectionBurn1', 'ArtifactAddRadiation1'),
    'FArtifactEye': ('ArtifactProtectionBurn1',),
    'CArtifactBun': ('ArtifactProtectionChemicalBurn2', 'ArtifactAddRadiation2'),
    'CArtifactThorn': ('ArtifactProtectionRadiation1',),
    'GArtifactWrenched': ('ArtifactProtectionStrike1',),
    'GArtifactBloodStone': ('ArtifactAdditionalInventoryWeight1', 'ArtifactAddRadiation1', 'ArtifactPenaltyLessWeightEffect1'),
    'GArtifactGraphiteBlock': ('ArtifactProtectionStrike1', 'ArtifactIncreaseRegenStamina1', 'ArtifactAddRadiation2'),
    'GArtifactSplitStone': ('ArtifactProtectionStrike2', 'ArtifactAddRadiation3'),
    'GArtifactTrunk': ('ArtifactIncreaseRegenStamina05', 'ArtifactAdditionalInventoryWeight05'),
    'GArtifactRubiksCube': ('ArtifactProtectionStrike3', 'ArtifactAddRadiation4'),
    'GArtifactSponge': ('ArtifactProtectionStrike05', 'ArtifactIncreaseRegenStamina1', 'ArtifactProtectionRadiation1'),
    'GArtifactHedgehog': ('ArtifactAdditionalInventoryWeight2', 'ArtifactProtectionRadiation2', 'ArtifactPenaltyLessWeightEffect2'),
    'GArtifactBud': ('ArtifactProtectionStrike2', 'ArtifactIncreaseRegenStamina2', 'ArtifactAddRadiation3'),
    'GArtifactPlane': ('ArtifactProtectionStrike05', 'ArtifactIncreaseRegenStamina05', 'ArtifactAddRadiation1'),
    'CArtifactMica': ('ArtifactProtectionRadiation1',),
    'CArtifactBubble': ('ArtifactProtectionRadiation2',),
    'CArtifactSlime': ('ArtifactProtectionRadiation1', 'ArtifactDurabilityIncrease1'),
    'CArtifactSlug': ('ArtifactProtectionRadiation1',),
    'CArtifactEchinus': ('ArtifactProtectionRadiation2',),
    'GArtifactCompass': ('ArtifactProtectionStrike4', 'ArtifactAddRadiation4'),
    'CArtifactKryptonite': ('ArtifactProtectionChemicalBurn1', 'ArtifactAddRadiation1'),
    'CArtifactBung': ('ArtifactAddRadiation1', 'ArtifactProtectionChemicalBurn1', 'ArtifactDurabilityIncrease1'),
    'EArtifactCrystalGlass': ('ArtifactIncreaseRegenStamina3', 'ArtifactAddRadiation3'),
    'CArtifactCottonWool': ('ArtifactProtectionChemicalBurn1', 'ArtifactAddRadiation1', 'ArtifactDurabilityIncrease1'),
    'GArtifactLandSlug': ('ArtifactProtectionStrike1', 'ArtifactAddRadiation1'),
    'CArtifactRosin': ('ArtifactProtectionChemicalBurn2', 'ArtifactAddRadiation2', 'ArtifactDurabilityIncrease2'),
    'CArtifactPlasticine': ('ArtifactProtectionChemicalBurn2', 'ArtifactAddRadiation2', 'ArtifactDurabilityIncrease2'),
    'EArtifactDope': ('ArtifactIncreaseRegenStamina4', 'ArtifactAddRadiation4'),
    'CArtifactBouncyBall': ('ArtifactProtectionRadiation3',),
    'CArtifactDevilsMushroom': ('ArtifactProtectionChemicalBurn3', 'ArtifactAddRadiation3', 'ArtifactDurabilityIncrease3'),
    'EArtifactChocolate': ('ArtifactProtectionShock1', 'ArtifactAddRadiation1'),
    'CArtifactLiquidStone': ('ArtifactProtectionRadiation4', 'ArtifactProtectionChemicalBurn4', 'ArtifactDurabilityIncrease4'),
}
