"""Audited scope identities only, never numeric game baselines.

See WEAPON_ITEM_DETAIL_RESEARCH.md and NPC_HELMET_DETAIL_RESEARCH.md.
"""

WEAPON_ITEMS = {'Deluxe_GunAK74_ST': ('Ultimate',
                       'GunAK74_ST',
                       'rifle',
                       ('Deluxe_GunAK74_ST', 'GunAK74_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunAK74_ST': (None, 'GunAK74_ST', 'rifle', ('GunAK74_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunAKU_PP': (None, 'GunAKU_PP', 'smg', ('GunAKU_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'GunAPB_HG': (None, 'GunAPB_HG', 'pistol', ('GunAPB_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'GunArevPrecise_AR': (None,
                       'GunArevPrecise_AR_GS',
                       'rifle',
                       ('GunArevPrecise_AR', 'GunArev_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunArev_ST': (None, 'GunArev_ST_GS', 'rifle', ('GunArev_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunBucket_PP': (None, 'GunBucket_PP', 'smg', ('GunBucket_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'GunD12_SG': (None, 'GunD12_SG', 'shotgun', ('GunD12_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'GunDnipro_ST': (None, 'GunDnipro_ST', 'rifle', ('GunDnipro_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunFora230_PP': (None, 'GunFora230_PP_GS', 'smg', ('GunFora230_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'GunFora_ST': (None, 'GunFora_ST', 'rifle', ('GunFora_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunG37V2_ST': (None,
                 'GunG37V2_ST',
                 'rifle',
                 ('GunG37V2_ST', 'GunG37_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunG37_ST': (None, 'GunG37_ST', 'rifle', ('GunG37_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunGP3A_DMR': (None, 'GunGP3A_DMR_GS', 'dmr', ('GunGP3A_DMR', 'TemplateDMR', 'TemplateWeapon', '[0]')),
 'GunGauss_SP': (None, 'GunGauss_SP', 'sniper', ('GunGauss_SP', 'TemplateSniper', 'TemplateWeapon', '[0]')),
 'GunGonta_SP': (None,
                 'GunGonta_SP_GS',
                 'sniper',
                 ('GunGonta_SP', 'GunThreeLine_SP', 'TemplateSniper', 'TemplateWeapon', '[0]')),
 'GunGrim_ST': (None, 'GunGrim_ST', 'rifle', ('GunGrim_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunGvintar_ST': (None, 'GunGvintar_ST', 'rifle', ('GunGvintar_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunIntegral_PP': (None, 'GunIntegral_PP', 'smg', ('GunIntegral_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'GunKharod_ST': (None, 'GunKharod_ST', 'rifle', ('GunKharod_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunKora_HG': (None, 'GunKora_HG', 'pistol', ('GunKora_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'GunLavina_ST': (None, 'GunLavina_ST', 'rifle', ('GunLavina_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunM10_HG': (None, 'GunM10_HG', 'smg', ('GunM10_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'GunM16_ST': (None, 'GunM16_ST', 'rifle', ('GunM16_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunM701_SP': (None, 'GunM701_SP', 'sniper', ('GunM701_SP', 'TemplateSniper', 'TemplateWeapon', '[0]')),
 'GunM860_SG': (None, 'GunM860_SG', 'shotgun', ('GunM860_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'GunMark_SP': (None, 'GunMark_SP', 'dmr', ('GunMark_SP', 'TemplateDMR', 'TemplateWeapon', '[0]')),
 'GunNightStalker_HG': (None,
                        'GunNightStalker_HG',
                        'pistol',
                        ('GunNightStalker_HG', 'GunKora_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'GunObrez_SG': (None, 'GunObrez_SG', 'shotgun', ('GunObrez_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'GunPKP_MG': (None, 'GunPKP_MG', 'mg', ('GunPKP_MG', 'TemplateMG', 'TemplateWeapon', '[0]')),
 'GunPM_HG': (None, 'GunPM_HG', 'pistol', ('GunPM_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'GunRam2_SG': (None, 'GunRam2_SG', 'shotgun', ('GunRam2_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'GunRhino_HG': (None, 'GunRhino_HG', 'pistol', ('GunRhino_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'GunRpg7_GL': (None, 'GunRpg7_GL', 'launcher', ('GunRpg7_GL', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'GunSKP_DMR': (None, 'GunSKP_DMR_GS', 'dmr', ('GunSKP_DMR', 'TemplateDMR', 'TemplateWeapon', '[0]')),
 'GunSPSA_SG': (None, 'GunSPSA_SG', 'shotgun', ('GunSPSA_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'GunSVDM_SP': (None, 'GunSVDM_SP', 'sniper', ('GunSVDM_SP', 'TemplateSniper', 'TemplateWeapon', '[0]')),
 'GunSVU_SP': (None, 'GunSVU_SP', 'sniper', ('GunSVU_SP', 'TemplateSniper', 'TemplateWeapon', '[0]')),
 'GunTOZ_SG': (None, 'GunTOZ_SG', 'shotgun', ('GunTOZ_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'GunThreeLine_SP': (None,
                     'GunThreeLine_SP_GS',
                     'sniper',
                     ('GunThreeLine_SP', 'TemplateSniper', 'TemplateWeapon', '[0]')),
 'GunUDP_HG': (None, 'GunUDP_HG', 'pistol', ('GunUDP_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'GunViper_PP': (None, 'GunViper_PP', 'smg', ('GunViper_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'GunZubr_PP': (None, 'GunZubr_PP', 'smg', ('GunZubr_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'Gun_Cavalier_SR': (None,
                     'Gun_Cavalier_SR_GS',
                     'sniper',
                     ('Gun_Cavalier_SR', 'GunM701_SP', 'TemplateSniper', 'TemplateWeapon', '[0]')),
 'Gun_Combatant_AR': (None,
                      'Gun_Combatant_AR_GS',
                      'rifle',
                      ('Gun_Combatant_AR', 'GunAK74_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Deadeye_HG': (None,
                    'GunUDP_Deadeye_HG',
                    'pistol',
                    ('Gun_Deadeye_HG', 'GunUDP_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'Gun_Decider_AR': (None,
                    'Gun_Decider_AR_GS',
                    'rifle',
                    ('Gun_Decider_AR', 'GunFora_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Drowned_AR': (None,
                    'Gun_Drowned_AR_GS',
                    'rifle',
                    ('Gun_Drowned_AR', 'GunAK74_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Encourage_HG': (None,
                      'Gun_Encourage_HG_GS',
                      'pistol',
                      ('Gun_Encourage_HG', 'GunAPB_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'Gun_GStreet_HG': (None,
                    'Gun_GStreet_HG_GS',
                    'smg',
                    ('Gun_GStreet_HG', 'GunM10_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'Gun_Gabion_AR': ('Deluxe',
                   'Gun_Gabion_AR_GS',
                   'rifle',
                   ('Gun_Gabion_AR', 'GunLavina_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Krivenko_HG': (None,
                     'Gun_Krivenko_HG_GS',
                     'pistol',
                     ('Gun_Krivenko_HG', 'GunUDP_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'Gun_Logarithm_SMG': ('Deluxe',
                       'Gun_Logarithm_SMG_GS',
                       'smg',
                       ('Gun_Logarithm_SMG', 'GunIntegral_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'Gun_Lummox_AR': (None,
                   'Gun_Lummox_AR_GS',
                   'rifle',
                   ('Gun_Lummox_AR', 'GunAK74_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Lynx_SR': (None,
                 'Gun_Lynx_SR_GS',
                 'sniper',
                 ('Gun_Lynx_SR', 'GunSVDM_SP', 'TemplateSniper', 'TemplateWeapon', '[0]')),
 'Gun_Margach_SG': ('Ultimate',
                    'Gun_Margach_SG_GS',
                    'shotgun',
                    ('Gun_Margach_SG', 'GunD12_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'Gun_Merc_AR': (None,
                 'Gun_Merc_AR_GS',
                 'rifle',
                 ('Gun_Merc_AR', 'GunGvintar_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_ModelSpecial_HG': ('Ultimate',
                         'Gun_ModelSpecial_HG_GS',
                         'pistol',
                         ('Gun_ModelSpecial_HG', 'GunRhino_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'Gun_Novator_AR': ('Ultimate',
                    'Gun_Novator_AR_GS',
                    'rifle',
                    ('Gun_Novator_AR', 'GunFora_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Partner_SR': (None,
                    'Gun_Partner_SR_GS',
                    'dmr',
                    ('Gun_Partner_SR', 'GunMark_SP', 'TemplateDMR', 'TemplateWeapon', '[0]')),
 'Gun_PistolMonolith_HG': ('Deluxe',
                           'Gun_Monolit_HG_GS',
                           'pistol',
                           ('Gun_PistolMonolith_HG', 'GunPM_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'Gun_Predator_SG': (None,
                     'Gun_Predator_SG_GS',
                     'shotgun',
                     ('Gun_Predator_SG', 'GunM860_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'Gun_ProjectY_HG': (None,
                     'Gun_Kaimanov_HG_GS',
                     'pistol',
                     ('Gun_ProjectY_HG', 'GunPM_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'Gun_RatKiller_SMG': (None,
                       'Gun_RatKiller_SMG_GS',
                       'smg',
                       ('Gun_RatKiller_SMG', 'GunZubr_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'Gun_RifleMonolith_AR': ('Deluxe',
                          'Gun_Monolit_AR_GS',
                          'rifle',
                          ('Gun_RifleMonolith_AR', 'GunM16_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_S15_AR': (None,
                'Gun_S15_AR',
                'rifle',
                ('Gun_S15_AR', 'GunGrim_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_SMGMonolith_SMG': ('Ultimate',
                         'Gun_SMGMonolith_SMG_GS',
                         'smg',
                         ('Gun_SMGMonolith_SMG', 'GunViper_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'Gun_SOFMOD_AR': (None,
                   'Gun_SOFMOD_AR_GS',
                   'rifle',
                   ('Gun_SOFMOD_AR', 'GunM16_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Shakh_SMG': (None,
                   'Gun_Shakh_SMG_GS',
                   'smg',
                   ('Gun_Shakh_SMG', 'GunViper_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'Gun_Sharpshooter_AR': (None,
                         'Gun_Sharpshooter_AR_GS',
                         'rifle',
                         ('Gun_Sharpshooter_AR', 'GunM16_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_ShotgunMonolith_SG': ('Deluxe',
                            'Gun_Monolit_SG_GS',
                            'shotgun',
                            ('Gun_ShotgunMonolith_SG', 'GunM860_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'Gun_Silence_SMG': (None,
                     'Gun_Silence_SMG_GS',
                     'smg',
                     ('Gun_Silence_SMG', 'GunAKU_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'Gun_Sledgehammer_SG': (None,
                         'Gun_Sledgehammer_SG_GS',
                         'shotgun',
                         ('Gun_Sledgehammer_SG', 'GunSPSA_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'Gun_Sotnyk_AR': (None,
                   'Gun_Sotnyk_AR_GS',
                   'rifle',
                   ('Gun_Sotnyk_AR', 'GunDnipro_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Spitfire_SMG': (None,
                      'Gun_Spitfire_SMG_GS',
                      'smg',
                      ('Gun_Spitfire_SMG', 'GunAKU_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'Gun_Spitter_SMG': (None,
                     'Gun_Spitter_SMG_GS',
                     'smg',
                     ('Gun_Spitter_SMG', 'GunBucket_PP', 'TemplateSMG', 'TemplateWeapon', '[0]')),
 'Gun_Star_HG': (None,
                 'Gun_Star_HG_GS',
                 'pistol',
                 ('Gun_Star_HG', 'GunPM_HG', 'TemplatePistol', 'TemplateWeapon', '[0]')),
 'Gun_Tank_MG': (None,
                 'Gun_Tank_MG_GS',
                 'mg',
                 ('Gun_Tank_MG', 'GunPKP_MG', 'TemplateMG', 'TemplateWeapon', '[0]')),
 'Gun_Texas_SG': (None,
                  'Gun_Texas_SG_GS',
                  'shotgun',
                  ('Gun_Texas_SG', 'GunRam2_SG', 'TemplateShotgun', 'TemplateWeapon', '[0]')),
 'Gun_Trophy_AR': (None,
                   'Gun_Trophy_AR_GS',
                   'rifle',
                   ('Gun_Trophy_AR', 'GunLavina_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Unknown_AR': (None,
                    'Gun_Unknown_AR_GS',
                    'rifle',
                    ('Gun_Unknown_AR', 'GunM16_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Veteran_AR': ('PreOrder',
                    'Gun_Veteran_AR_GS',
                    'rifle',
                    ('Gun_Veteran_AR', 'GunGvintar_ST', 'TemplateRifle', 'TemplateWeapon', '[0]')),
 'Gun_Whip_SR': (None,
                 'Gun_Whip_SR_GS',
                 'sniper',
                 ('Gun_Whip_SR', 'GunSVU_SP', 'TemplateSniper', 'TemplateWeapon', '[0]')),
 'Gun_Zvirolov_SR': ('Deluxe',
                     'Gun_Zvirolov_SR_GS',
                     'sniper',
                     ('Gun_Zvirolov_SR', 'GunM701_SP', 'TemplateSniper', 'TemplateWeapon', '[0]'))}

HELMET_POOLS = {('GeneralNPC_Bandit_Armor', '[2]'): ('ERank::Experienced, ERank::Veteran, ERank::Master',
                                      '',
                                      '[0]',
                                      'Light_Bandit_Helmet'),
 ('GeneralNPC_Corpus_Armor', '[3]'): ('ERank::Newbie, ERank::Experienced', '', '[0]', 'Light_Military_Helmet'),
 ('GeneralNPC_Corpus_Armor', '[4]'): ('ERank::Veteran', '', '[0]', 'Heavy_Military_Helmet'),
 ('GeneralNPC_Duty_Armor', '[4]'): ('ERank::Newbie', '', '[0]', 'Light_Duty_Helmet'),
 ('GeneralNPC_Duty_Armor_Experienced_var1', '[1]'): ('', '', '[0]', 'Heavy_Duty_Helmet'),
 ('GeneralNPC_Freedom_Armor', '[4]'): ('ERank::Experienced', '', '[0]', 'Heavy_Svoboda_Helmet'),
 ('GeneralNPC_Mercenaries_Armor', '[4]'): ('ERank::Newbie, ERank::Experienced',
                                           '',
                                           '[0]',
                                           'Light_Mercenaries_Helmet'),
 ('GeneralNPC_Militaries_Armor', '[3]'): ('ERank::Newbie', '', '[0]', 'Light_Military_Helmet'),
 ('GeneralNPC_Militaries_Armor', '[4]'): ('ERank::Experienced', '', '[0]', 'Battle_Military_Helmet'),
 ('GeneralNPC_Militaries_Armor_var2', '[1]'): ('', '', '[0]', 'Heavy_Military_Helmet'),
 ('GeneralNPC_Monolith_Armor', '[3]'): ('ERank::Newbie, ERank::Experienced', '', '[0]', 'Battle_Military_Helmet'),
 ('GeneralNPC_Neutral_CloseCombat_ItemGenerator', '[13]'): ('ERank::Newbie, ERank::Experienced',
                                                            '',
                                                            '[0]',
                                                            'Light_Neutral_Helmet'),
 ('GeneralNPC_Neutral_CloseCombat_ItemGenerator', '[14]'): ('ERank::Veteran, ERank::Master',
                                                            '',
                                                            '[0]',
                                                            'Light_Neutral_Helmet'),
 ('GeneralNPC_Neutral_Recon_ItemGenerator', '[12]'): ('ERank::Newbie, ERank::Experienced',
                                                      '',
                                                      '[0]',
                                                      'Light_Neutral_Helmet'),
 ('GeneralNPC_Neutral_Recon_ItemGenerator', '[13]'): ('ERank::Veteran, ERank::Master',
                                                      '',
                                                      '[0]',
                                                      'Light_Neutral_Helmet'),
 ('GeneralNPC_Neutral_Sniper_ItemGenerator', '[13]'): ('ERank::Newbie, ERank::Experienced',
                                                       '',
                                                       '[0]',
                                                       'Light_Neutral_Helmet'),
 ('GeneralNPC_Neutral_Sniper_ItemGenerator', '[14]'): ('ERank::Veteran, ERank::Master',
                                                       '',
                                                       '[0]',
                                                       'Light_Neutral_Helmet'),
 ('GeneralNPC_Neutral_Stormtrooper_ItemGenerator', '[10]'): ('ERank::Veteran, ERank::Master',
                                                             '',
                                                             '[0]',
                                                             'Light_Neutral_Helmet'),
 ('GeneralNPC_Neutral_Stormtrooper_ItemGenerator', '[9]'): ('ERank::Newbie, ERank::Experienced',
                                                            '',
                                                            '[0]',
                                                            'Light_Neutral_Helmet'),
 ('GeneralNPC_Noon_Armor', '[3]'): ('ERank::Newbie, ERank::Experienced', '', '[0]', 'Battle_Military_Helmet'),
 ('GeneralNPC_Noon_Armor', '[4]'): ('ERank::Veteran', '', '[0]', 'Heavy_Military_Helmet'),
 ('GeneralNPC_Spark_Armor', '[3]'): ('ERank::Newbie, ERank::Experienced', '', '[0]', 'Battle_Military_Helmet'),
 ('GeneralNPC_Varta_Armor', '[3]'): ('ERank::Experienced, ERank::Veteran', '', '[0]', 'Heavy_Varta_Helmet')}
