"""Anzeigenamen fuer Waffen und Ruestungen (reine UI-/Suchhilfe).

Quelle: Community-Masterliste des Besitzers (ChatGPT-Recherche,
02.09.2026, Gamer-Guides/Nexus/offizielle Editions-Seite) — hier steht
NUR, was gegen die echten Spieldaten dieses Stands verifiziert wurde
(jede SID existiert im jeweiligen Baum; Pruefskript siehe Chat vom
02.09., Wiederholung: tests/test_names.py). Spielwerte kommen weiterhin
IMMER live aus den Daten — diese Datei beschriftet nur.

- WEAPON_ALIASES: {WeaponGeneralSetup-SID: Anzeigename} fuer den
  Waffen-Baum (Zeilen zeigen SID + Name, die Suche findet beide).
- ARMOR_ALIASES: {Item-SID: Anzeigename} fuer den Armor-Baum
  (ersetzt das generierte Label aus armor_label(), wo bekannt).

Namen sind Lokalisierungs-, keine Spieldaten — bei Luecken bleibt die
SID sichtbar, lieber ehrlich technisch als falsch geraten.
"""

WEAPON_ALIASES = {
    'GunAK74_ST': 'AKM-74S',
    'GunAKU_PP': 'AKM-74U',
    'GunAPB_HG': 'APSB',
    'GunArev_ST_GS': 'ARev',
    'GunBucket_PP': 'Buket S-2',
    'GunD12_SG': 'Saiga D-12',
    'GunDnipro_ST': 'Dnipro',
    'GunFora230_PP_GS': 'Fora-230',
    'GunFora_ST': 'Fora-221',
    'GunG37_ST': 'GP37',
    'GunGP3A_DMR_GS': 'GP3A',
    'GunGauss_SP': 'Gauss Gun',
    'GunGauss_Scar_SP': 'EM-1',
    'GunGonta_SP_GS': "Honta's Drahunka",
    'GunGrim_ST': 'Grom S-14',
    'GunGvintar_ST': 'VS Vintar',
    'GunIntegral_PP': 'Integral-A',
    'GunKharod_ST': 'Kharod',
    'GunKora_HG': 'Kora-1911',
    'GunLavina_ST': 'AS Lavina',
    'GunM10_HG': 'M10 Gordon',
    'GunM16_ST': 'AR416',
    'GunM701_SP': 'M701 Super',
    'GunM860_SG': 'M860 Cracker',
    'GunMark_SP': 'Mark I EMR',
    'GunNightStalker_HG': 'Night Stalker',
    'GunObrez_SG': 'Boomstick',
    'GunPKP_Korshunov_MG_GS': 'Beast',
    'GunPKP_MG': 'RPM-74',
    'GunPM_HG': 'PTM',
    'GunRam2_SG': 'Ram-2',
    'GunRhino_HG': 'Rhino',
    'GunRpg7_GL': 'RPG-7U',
    'GunSKP_DMR_GS': 'SKP',
    'GunSPSA_SG': 'SPSA-14',
    'GunSVDM_SP': 'SVDM-2',
    'GunSVU_SP': 'SVU-MK S-3',
    'GunTOZ_SG': 'TOZ-34',
    'GunThreeLine_SP_GS': 'Three-Line Rifle',
    'GunUDP_Deadeye_HG': 'Deadeye',
    'GunUDP_HG': 'UDP Compact',
    'GunViper_PP': 'Viper-5',
    'GunZubr_PP': 'Zubr-19',
    'Gun_Cavalier_SR_GS': 'Cavalier',
    'Gun_Combatant_AR_GS': 'Combatant',
    'Gun_Decider_AR_GS': 'Decider',
    'Gun_Drowned_AR_GS': 'Drowned',
    'Gun_Encourage_HG_GS': 'Encourage',
    'Gun_GStreet_HG_GS': 'Gangster',
    'Gun_Gabion_AR_GS': "Lavina SA 'Gabion'",
    'Gun_Kaimanov_HG_GS': 'Labyrinth IV',
    'Gun_Krivenko_HG_GS': 'Gambit',
    'Gun_Logarithm_SMG_GS': "Integral-A 'Riemann'",
    'Gun_Lummox_AR_GS': "Valik Lummox's AKM-74S",
    'Gun_Lynx_SR_GS': 'Lynx',
    'Gun_Margach_SG_GS': "D12 'Margach D12MT'",
    'Gun_Merc_AR_GS': 'Merc',
    'Gun_ModelSpecial_HG_GS': "Rhino 'Model Competitor'",
    'Gun_Monolit_AR_GS': "AR416 'Monolith'",
    'Gun_Monolit_HG_GS': "PTM 'Monolith'",
    'Gun_Monolit_SG_GS': "M860 'Monolith'",
    'Gun_Novator_AR_GS': "Fora-221 'Lullaby'",
    'Gun_Partner_SR_GS': 'Partner',
    'Gun_Predator_SG_GS': 'Predator',
    'Gun_RatKiller_SMG_GS': 'Rat Killer',
    'Gun_S15_AR': 'Grom S-15',
    'Gun_SMGMonolith_SMG_GS': "Viper 'Monolith'",
    'Gun_SOFMOD_AR_GS': 'SOFMOD',
    'Gun_Shakh_SMG_GS': "Shah's Mate",
    'Gun_Sharpshooter_AR_GS': 'Clusterfuck',
    'Gun_Silence_SMG_GS': 'Special',
    'Gun_Sledgehammer_SG_GS': 'Sledgehammer',
    'Gun_Sotnyk_AR_GS': 'Sotnyk',
    'Gun_Spitfire_SMG_GS': 'Spitfire',
    'Gun_Spitter_SMG_GS': 'Spitter',
    'Gun_Tank_MG_GS': 'Glutton',
    'Gun_Texas_SG_GS': 'Texan',
    'Gun_Trophy_AR_GS': 'Trophy',
    'Gun_Unknown_AR_GS': "Unknown Stalker's AR416",
    'Gun_Veteran_AR_GS': "VS Vintar 'Veteran'",
    'Gun_Whip_SR_GS': 'Whip',
    'Gun_Zvirolov_SR_GS': "M701 'Hunter'",
}

ARMOR_ALIASES = {
    'Anomaly_Scientific_Armor': 'SSP-99 Ecologist',
    'BattleExoskeleton_Varta_Armor': 'Operator Exoskeleton',
    'Battle_Dolg_Armor': 'PSZ-5D Universal Protection',
    'Battle_Dolg_End_Armor': 'X7 Suit',
    'Battle_Military_Helmet': 'Ballistic Helmet',
    'Battle_Monolith_Armor': 'Zircon Suit',
    'Battle_Spark_Armor': 'PSZ-5I Hawk',
    'Battle_Svoboda_Armor': 'PSZ-5V Guardian of Freedom Suit',
    'Battle_Varta_Armor': 'PSZ-20W Convoy',
    'Default_Military_Armor': 'PSZ-7 Military Body Armor',
    'Exoskeleton_Dolg_Armor': 'Cuirass Exoskeleton',
    'Exoskeleton_Mercenaries_Armor': 'Brummbar Exoskeleton',
    'Exoskeleton_Monolith_Armor': 'Diamond Exoskeleton',
    'Exoskeleton_Neutral_Armor': 'Exoskeleton',
    'Exoskeleton_Svoboda_Armor': 'Liberty Exoskeleton',
    'Heavy2_Military_Armor': 'Berill-5M Armored Suit',
    'HeavyAnomaly_Monolith_Armor': 'Corundum Suit',
    'HeavyAnomaly_SIRCA_Armor': 'SSP-100M SIRCAA Suit',
    'HeavyAnomaly_Scientific_Armor': 'SSP-100 Discovery',
    'HeavyAnomaly_Spark_Armor': 'SSP-100I Survey',
    'HeavyBattle_Spark_Armor': 'PSZ-9I Falcon',
    'HeavyExoskeleton_Dolg_Armor': 'Shield of Duty Exosuit',
    'HeavyExoskeleton_Monolith_Armor': 'Ruby Exosuit',
    'HeavyExoskeleton_Svoboda_Armor': 'Bulwark Exosuit',
    'HeavyExoskeleton_Varta_Armor': "Ward Exoskeleton 'PSZ-21W Shturm'",
    'Heavy_Dolg_Armor': 'PSZ-9D Duty Armor',
    'Heavy_Duty_Helmet': 'Sphere M20 Helmet',
    'Heavy_Mercenaries_Armor': 'PSZ-9N Wolfhound',
    'Heavy_Military_Helmet': 'Tactical Helmet',
    'Heavy_Svoboda_Armor': 'PSZ-12V Bulat',
    'Heavy_Svoboda_Helmet': 'Mask-1 Helmet',
    'Heavy_Varta_Helmet': 'Aeroprotection Gas Mask',
    'Jacket_Bandit_Armor': 'Armored Bandit Jacket',
    'Jemmy_Neutral_Armor': 'Leather Jacket',
    'Light_Bandit_Helmet': 'PG-4 Facehugger Gas Mask',
    'Light_Duty_Helmet': 'Aurora Gas Mask',
    'Light_Mercenaries_Armor': 'Mercenary Suit',
    'Light_Mercenaries_Helmet': 'PA-7 Gas Mask',
    'Light_Military_Helmet': 'PA-10 Gas Mask',
    'Light_Neutral_Helmet': 'Optician Gas Mask',
    'Middle_Bandit_Armor': 'Marauder Suit',
    'Nasos_Neutral_Armor': "OZK Explorer's Suit",
    'Newbee_Neutral_Armor': 'Debut Suit',
    'Rook_Dolg_Armor': 'Recruit Suit',
    'Rook_Svoboda_Armor': 'Wind of Freedom Suit',
    'SEVA_Dolg_Armor': 'SEVA-D Suit',
    'SEVA_Monolith_Armor': "SEVA Suit 'Wanderer'",
    'SEVA_Neutral_Armor': 'SEVA Suit',
    'SEVA_Spark_Armor': 'SEVA-I Suit',
    'SEVA_Svoboda_Armor': 'SEVA-V Suit',
    'SkinJacket_Bandit_Armor': 'Bandit Jacket',
    'UltraLight_Mercenaries_Armor': 'Ultra-Lightweight Mercenary Suit',
    'Zorya_Neutral_Armor': 'Sunrise Suit',
    'Zorya_Tourist_Armor': 'Tourist Suit',
}
